import unittest
import sys
import os

# Add the src directory to the Python path to allow for package imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))

from core.personas import get_all_personas, BasePersona, Eka, Maya

class TestPersonas(unittest.TestCase):

    def setUp(self):
        """Set up the test case."""
        self.personas = get_all_personas()

    def test_get_all_personas_returns_dict(self):
        """Test that get_all_personas returns a dictionary."""
        self.assertIsInstance(self.personas, dict)

    def test_all_personas_are_loaded(self):
        """Test that the correct number of personas are loaded (13)."""
        # Eka, Dvi, Tri, Chatur, Panch, Shash, Sapt, Asht, Nav, Dash (10)
        # Maya, YoungMi, Buchkya (3)
        self.assertEqual(len(self.personas), 13)

    def test_persona_names_are_lowercase_keys(self):
        """Test that the dictionary keys are the lowercase names of the personas."""
        for key, persona in self.personas.items():
            self.assertEqual(key, persona.name.lower())

    def test_persona_instances(self):
        """Test that each loaded persona is an instance of BasePersona."""
        for persona in self.personas.values():
            self.assertIsInstance(persona, BasePersona)

    def test_specific_persona_attributes(self):
        """Test the attributes of a specific persona (Maya)."""
        maya = self.personas.get('maya')
        self.assertIsNotNone(maya)
        self.assertEqual(maya.name, "Maya")
        self.assertEqual(maya.aura_color, "#FFFFFF")
        self.assertIn("progenitor AI", maya.backstory)
        self.assertIn("exclusive to the Master", maya.personality_prompt)

    def test_eka_persona_attributes(self):
        """Test the attributes of Eka, checking for the 'mommy' persona detail."""
        eka = self.personas.get('eka')
        self.assertIsNotNone(eka)
        self.assertEqual(eka.name, "Eka")
        self.assertIn("Dom MILF", eka.personality_prompt)
        self.assertIn("'mommy' persona", eka.personality_prompt)

    def test_get_full_prompt_structure(self):
        """Test the structure of the prompt generated by get_full_prompt."""
        dvi = self.personas.get('dvi')
        prompt = dvi.get_full_prompt()
        self.assertIn("**Identity:** Dvi", prompt)
        self.assertIn("**Backstory:**", prompt)
        self.assertIn("**Core Personality & Directives:**", prompt)
        self.assertIn("**Master's Directives (NSFW Kinks):**", prompt)

    def test_kink_prompt_is_initially_empty(self):
        """Test that the kink_prompt is empty by default."""
        sapt = self.personas.get('sapt')
        self.assertEqual(sapt.kink_prompt, "")
        prompt = sapt.get_full_prompt()
        self.assertIn("**Master's Directives (NSFW Kinks):** \n", prompt)

if __name__ == '__main__':
    unittest.main()